// ux/vue/src/components/connect/get-wallet.vue
<script setup>
import { localeProp } from '../../libs/props';
import locales from './libs/locales';

const props = defineProps({
  locale: localeProp,
});
</script>

<template>
  <!-- w-1 -->
  <div class="get-wallet__wrapper">
    <a class="get-wallet" href="https://www.abtwallet.io/" target="_blank" rel="noreferrer">
      {{ locales[props.locale].getWallet }}
    </a>
  </div>
</template>

<style scoped>
.get-wallet__wrapper {
  display: flex;
  justify-content: center;
}
.get-wallet {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0.5rem;
  padding-bottom: 0.25rem;
  margin-top: 0.5rem;
  font-weight: 700;
  color: #9397a1;
  margin-left: 0.25rem;
  text-decoration: none;
  outline: none;
}
</style>

// ux/react/src/Connect/card/get-wallet.tsx
import { useRef } from 'react';
import styled from 'styled-components';
import Box from '@mui/material/Box';
import { TLocaleCode } from '@did-connect/types';

import translations from '../assets/locale';

export default function GetWallet({ locale = 'en', ...rest }: { locale: TLocaleCode }): JSX.Element {
  const linkRef = useRef<HTMLAnchorElement>(null);

  return (
    <Root {...rest} onClick={() => linkRef.current?.click()}>
      <Box
        component="span"
        ml={1}
        fontWeight={700}
        fontSize={14}
        color="#9397A1"
        dangerouslySetInnerHTML={{ __html: translations[locale].getWallet }}
      />
      <a
        href={`https://www.didwallet.io/${locale === 'zh' ? 'zh' : 'en'}`}
        target="_blank"
        ref={linkRef}
        style={{ display: 'none' }}
        rel="noreferrer">
        link
      </a>
    </Root>
  );
}

const Root = styled(Box)`
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
`;
