// packages/vue/src/components/avatar/did-motif.vue
<script setup>
import { ref, onMounted } from 'vue';
import { update } from '@arcblock/did-motif';

const props = defineProps({
  did: {
    type: String,
    required: true,
  },
  responsive: {
    type: Boolean,
    default: false,
  },
  size: {
    type: Number,
    default: 200,
  },
  animation: {
    type: Boolean,
    default: false,
  },
  shape: {
    type: String,
    default: '',
    validator: (v) => ['', 'rectangle', 'square', 'hexagon', 'circle'].includes(v),
  },
});
const svgRef = ref(null);

onMounted(() => {
  update(svgRef.value, props.did, { size: props.size, animation: props.animation, shape: props.shape });
});
</script>

<template>
  <!-- fix avatar 显示问题 (safari 下父容器为 flex 时 inline svg 显示不出来, 需要明确指定 width) -->
  <svg v-if="props.responsive" ref="svgRef" style="width: 100%; max-height: 100%" />
  <span
    v-else
    :style="{
      display: 'inline-block',
      width: `${props.size}px`,
      height: `${props.size}px`,
    }"
  >
    <svg ref="svgRef" />
  </span>
</template>

// ux/react/src/Avatar/did-motif.tsx
import { useRef, useLayoutEffect } from 'react';
import { update } from '@arcblock/did-motif';

const defaultProps = {
  size: 200,
  animation: false,
  responsive: false,
  shape: null,
};

type Props = {
  did: string;
  size?: number;
  animation?: boolean;
  responsive?: boolean;
  shape?: number;
} & typeof defaultProps;

export default function DIDMotif({ did, size, animation, shape, responsive, ...rest }: Props): JSX.Element {
  const svgRef = useRef(null);

  useLayoutEffect(() => {
    update(svgRef.current, did, { size, animation, shape });
  }, [did, size, shape]); // eslint-disable-line

  if (responsive) {
    // fix avatar 显示问题 (safari 下父容器为 flex 时 inline svg 显示不出来, 需要明确指定 width)
    const styles = { ...rest.style, width: '100%' };
    return <svg ref={svgRef} {...rest} style={styles} />;
  }

  return (
    <span {...rest} style={{ display: 'inline-block', width: size, height: size, ...rest.style }}>
      <svg ref={svgRef} />
    </span>
  );
}

DIDMotif.defaultProps = defaultProps;
