// ux/react/src/Connect/index.js
import React from 'react';
import PropTypes from 'prop-types';
import useToken from './hooks/token';
import BasicConnect from './basic';
import { BrowserEnvProvider } from './contexts/browser';
import withDialog from './withDialog';
import { withWebWalletSWKeeper } from '../WebWalletSWKeeper';
import '@fontsource/lato/400.css';
import '@fontsource/lato/700.css';

/**
 * - 将 token state (useToken) 提升到这里 (提升 BasicConnect 上层, 方便 BasicConnect 独立测试)
 */
function Connect({
  onClose,
  onSuccess,
  onError,
  action,
  prefix,
  socketUrl,
  checkFn,
  checkInterval,
  checkTimeout,
  extraParams,
  locale,
  tokenKey,
  encKey,
  baseUrl,
  enableAutoConnect,
  ...rest
}) {
  if (typeof checkFn !== 'function') {
    throw new Error('Cannot initialize did connect component without a fetchFn');
  }

  const { state, generate, cancelWhenScanned } = useToken({
    action,
    baseUrl,
    checkFn,
    checkInterval,
    checkTimeout,
    extraParams,
    prefix,
    socketUrl,
    onClose,
    onError,
    onSuccess,
    locale,
    tokenKey,
    encKey,
    enableAutoConnect,
  });

  const connectProps = {
    ...rest,
    tokenState: state,
    generate,
    cancelWhenScanned,
    locale,
    tokenKey,
    encKey,
  };

  return (
    <BrowserEnvProvider>
      <BasicConnect {...connectProps} />
    </BrowserEnvProvider>
  );
}

Connect.propTypes = {
  onClose: PropTypes.func,
  onError: PropTypes.func,
  onSuccess: PropTypes.func.isRequired,
  action: PropTypes.string.isRequired,
  checkFn: PropTypes.func.isRequired,
  prefix: PropTypes.string,
  socketUrl: PropTypes.string,
  checkInterval: PropTypes.number,
  checkTimeout: PropTypes.number,
  extraParams: PropTypes.object,
  locale: PropTypes.oneOf(['en', 'zh']),
  tokenKey: PropTypes.string,
  encKey: PropTypes.string,
  baseUrl: PropTypes.string,
  enableAutoConnect: PropTypes.bool,
};

Connect.defaultProps = {
  prefix: '/api/did',
  socketUrl: '',
  onClose: () => {},
  onError: () => {},
  checkInterval: 2000,
  checkTimeout: 60000, // 1 minute
  extraParams: {},
  locale: 'en',
  tokenKey: '_t_',
  encKey: '_ek_',
  baseUrl: '',
  enableAutoConnect: true,
};

export default withWebWalletSWKeeper(withDialog(Connect));

// packages/vue/src/components/connect/connect.vue
<script setup>
import { computed } from 'vue';
import { pick, omit } from 'lodash-es';
import { PREFIX } from '../session/constants';
import useSessionState from './hooks/use-session-state';
import BasicConnect from './basic-connect.vue';

const props = defineProps({
  action: {
    type: String,
    required: true,
  },
  checkFn: {
    type: Function,
    required: true,
  },
  prefix: {
    type: String,
    default: PREFIX,
  },
  socketUrl: String,
  checkInterval: {
    type: Number,
    default: 2000,
  },
  checkTimeout: {
    type: Number,
    default: 60 * 1000,
  },
  extraParams: {
    type: Object,
    default: () => ({}),
  },
  locale: {
    type: String,
    default: 'en',
    validator: (v) => ['en', 'zh'].includes(v),
  },
  tokenKey: {
    type: String,
    default: '_t_',
  },
  encKey: {
    type: String,
    default: '_ek_',
  },
  baseUrl: String,
  enableAutoConnect: {
    type: Boolean,
    default: true,
  },
  open: {
    type: Boolean,
    default: false,
  },
  enabledConnectTypes: {
    type: Array,
    default: () => ['web', 'mobile'],
  },
  webWalletUrl: {
    type: String,
    default: '',
  },
  showDownload: {
    type: Boolean,
    default: true,
  },
  qrcodeSize: {
    type: Number,
    default: 184,
  },
  messages: {
    type: Object,
    required: true,
  },
});
const emits = defineEmits(['success', 'close', 'error', 'recreateSession']);

if (typeof props.checkFn !== 'function') {
  throw new Error('Cannot initialize did connect component without a fetchFn');
}

const { state, generate, cancelWhenScanned } = useSessionState({
  ...pick(props, [
    'action',
    'baseUrl',
    'checkFn',
    'checkInterval',
    'checkTimeout',
    'prefix',
    'extraParams',
    'locale',
    'tokenKey',
    'encKey',
    'socketUrl',
    'enableAutoConnect',
    'open',
  ]),
  onClose(...args) {
    emits('close', ...args);
  },
  onError(...args) {
    emits('error', ...args);
  },
  onSuccess(...args) {
    emits('success', ...args);
  },
});

const connectProps = computed(() => {
  return {
    state,
    generate,
    cancelWhenScanned,
    ...omit(props, [
      'action',
      'baseUrl',
      'open',
      'prefix',
      'socketUrl',
      'checkFn',
      'checkInterval',
      'checkTimeout',
      'extraParams',
      'enableAutoConnect',
    ]),
  };
});
</script>

<template>
  <BasicConnect v-if="props.open" v-bind="connectProps" />
</template>
