// ux/react/src/Button/index.js
import React from 'react';
import PropTypes from 'prop-types';
import Button from '@arcblock/ux/lib/Button';
import ConnectLogo from '@arcblock/icons/lib/ConnectLogo';

/**
 * ConnectButton
 */
export default function ConnectButton({ children, ...rest }) {
  return (
    <Button color="did" variant="contained" {...rest}>
      <span style={{ fontWeight: 400 }}>{children || 'Continue With'}</span>
      <ConnectLogo style={{ width: 'auto', height: '1.2em', margin: '0 4px 0 8px' }} />
    </Button>
  );
}

ConnectButton.propTypes = {
  children: PropTypes.any,
};

ConnectButton.defaultProps = {
  children: '',
};

// packages/vue/src/components/button/button.vue
<script setup>
import ConnectLogo from '@arcblock/icons/src/icons/connect-logo.svg?component';
import BaseButton from './base-button.vue';
</script>

<template>
  <BaseButton v-bind="$attrs" color="did">
    <span class="font-400">
      <slot>Continue With</slot>
    </span>
    <ConnectLogo class="h-[1.2em] w-auto mr-[4px] ml-[8px]" />
  </BaseButton>
</template>
